worker_processes  auto;

error_log  /dev/stderr notice;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
    multi_accept on;
}

http {    
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent '
                    'rt=$request_time urt=$upstream_response_time '
                    '"$http_referer" "$http_user_agent"';

    access_log /dev/stdout main;

    limit_req_zone $binary_remote_addr zone=vm:10m rate=30r/s;

    map $ssl_client_verify $mtls_fail {
        default 1;
        SUCCESS 0;
    }
    
    upstream vmagent {
        server vmagent:8429;
    }

    upstream alloy {
        server alloy:12345;
    }

    server {
        listen 8428 ssl;
        server_name vm-reverce-proxy;

	    ssl_certificate        /etc/nginx/certs/vm.crt;
	    ssl_certificate_key    /etc/nginx/certs/vm.key;
	    ssl_client_certificate /etc/nginx/certs/ca-chain.crt;
	    
        ssl_verify_client optional_no_ca;
	    ssl_verify_depth 2;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        ssl_session_tickets off;

        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 1d;

        add_header Strict-Transport-Security "max-age=63072000" always;

        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location /agent/ {
            include /etc/nginx/common_security.conf;
            include proxy_params;

            proxy_pass http://vmagent/;
        }

        location / {
            include /etc/nginx/common_security.conf;
            include proxy_params;

            proxy_pass http://alloy/;
        }

        location /health {
            auth_basic off;

            return 200 'ok';
        }
    }

    include /etc/nginx/proxy_params;
}
