name: monitoring

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    mem_limit: 256m
    cpus: 0.5
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/metrics"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  docker-state-exporter:
    image: karugaru/docker_state_exporter
    container_name: docker-state-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:8082:8080"
    mem_limit: 128m
    cpus: 0.25
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/metrics"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "127.0.0.1:9110:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
    mem_limit: 128m
    cpus: 0.25
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9100/metrics"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  vmagent:
    depends_on:
      node-exporter:
        condition: service_healthy
      docker-state-exporter:
        condition: service_healthy
      cadvisor:
        condition: service_healthy
    volumes:
      - ../vm-agent/configs/prometheus.yml:/etc/prometheus/configs/prometheus.yml
