{
 "title": "Docker overview",
 "description": "Docker overview включает следующие экспортеры для каждого хоста с докером: Cadvisor, Docker state exporter, Node exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Datasource", "query": "prometheus" },
   { "name": "host_node_exporter_job_name", "query": "node-exporter" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "container_name",
    "label": "Container",
    "query": {
     "query": "label_values(container_state_status{instance=\"$instance\"},name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(name) (container_last_seen{instance=\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "container_state_status{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Docker workloads",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "container_state_status{name=~\"$container_name\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$container_name\",instance=\"$instance\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Created",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=~\"$container_name\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 25 },
   "targets": [
    {
     "expr": "count by(name) (count_over_time(container_last_seen{name=~\"$container_name\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{name=~\"$container_name\",container_label_org_label_schema_group=\"\",instance=\"$instance\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{name=~\"$container_name\",container_label_org_label_schema_group=\"\",instance=\"$instance\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{name=~\"$container_name\",container_label_org_label_schema_group=\"\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{name=~\"$container_name\",container_label_org_label_schema_group=\"\",instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Host metricks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Prometheus Exporters Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "up{job=~\"cadvisor|vmagent|docker-state-exporter|node-exporter\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 5, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"system\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"user\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"nice\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"iowait\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"irq\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"softirq\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"steal\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\", mode=\"idle\",instance=\"$instance\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes{job=\"$host_node_exporter_job_name\",instance=\"$instance\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"$host_node_exporter_job_name\",device!~'rootfs',instance=\"$instance\"}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^.*\",instance=\"$instance\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\"$container_name\",instance=\"$instance\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{name=~\"$container_name\",instance=\"$instance\"})/86400",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_state_status{name=~\"$container_name\", job=\"$host_node_exporter_job_name\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage by Container",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{name=~\"$container_name\", instance=\"$instance\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$container_name\",instance=\"$instance\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$container_name\",instance=\"$instance\"}[$__rate_interval])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}