- job_name: vmagent
  static_configs:
  - targets:
    - vmagent:8429

- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: alloy
  static_configs:
  - targets:
    - alloy-instance:12345
